/* =============================================================================
 * yolo_weights.h
 *
 * Pre-baked YOLO-Nano weights for L0 (CONV 3x3 1->4) and L3 (FC 36->20).
 * Generated by benchmarks/yolo_nano/tf_golden_yolo_nano.py and dumped from
 * benchmarks/yolo_nano/golden_yolo_wgts_l0.memh / golden_yolo_wgts_l3.memh.
 *
 * Build step:
 *     python3 software/vitis/scripts/memh_to_c.py
 *         benchmarks/yolo_nano/golden_yolo_wgts_l0.memh
 *         benchmarks/yolo_nano/golden_yolo_wgts_l3.memh
 *         > software/vitis/src/yolo_weights.c
 *
 * The C file is generated on demand. This header just declares the symbols.
 * ============================================================================= */
#ifndef YOLO_WEIGHTS_H_
#define YOLO_WEIGHTS_H_

#include "xil_types.h"
#include "dnn_accel.h"  /* YOLO_WGT_L0_LEN, YOLO_WGT_L3_LEN */

extern const s16 yolo_wgt_l0[YOLO_WGT_L0_LEN];
extern const s16 yolo_wgt_l3[YOLO_WGT_L3_LEN];

#endif /* YOLO_WEIGHTS_H_ */
