// ===========================================================================
// tb_zedboard_timing.v
// Behavioral timing-verification testbench for the streaming DNN accelerator
// targeting the ZedBoard (XC7Z020-CLG484-1, speed grade -1).
//
// What this tests
// ---------------
// 1. FUNCTIONAL CORRECTNESS at Zedboard's safe PL clock (100 MHz / 10 ns).
//    The optimizer's analytical estimate was for a 200 MHz target; this run
//    re-validates the design at the actual deploy frequency.
//
// 2. SETUP / HOLD MARGIN on the key control signals (start_inference,
//    load_weights, rst) with a parameterized combinational delay injected
//    between the testbench drivers and the DUT inputs.  This models a worst-
//    case routed path from the source FF (Tcko), through fabric routing and
//    combinational logic (T_COMB), to the destination FF input (Tsetup).
//
// 3. SLACK REPORTING against the actual clock period:
//        slack = T_period - T_cko - T_comb - T_setup - T_uncert
//    A positive slack is timing-met; a negative slack would fail STA in
//    Vivado.  This TB asserts PASS only if slack >= 0.
//
// Why behavioral (not post-impl)
// ------------------------------
// True post-implementation timing simulation requires SDF back-annotation
// generated by Vivado after place-and-route.  Icarus does not support SDF
// annotation, so this TB instead injects analytic delays at the TB level —
// same numerical checks, just at the source.  See scripts/vivado_timing.tcl
// for the production flow.
//
// Speed-grade XC7Z020-1 reference values (used as defaults)
// --------------------------------------------------------
//   FDRE Tcko (clk-to-Q)              T_CKO_NS    = 0.50 ns
//   FDRE Tas  (setup)                 T_SETUP_NS  = 0.30 ns
//   FDRE Tah  (hold)                  T_HOLD_NS   = 0.10 ns
//   Modeled comb path (worst routed)  T_COMB_NS   = 7.50 ns
//   Clock uncertainty (jitter+skew)   T_UNCERT_NS = 0.25 ns
//   ----------------------------------------------------------
//   slack @ 10 ns = 10 - 0.5 - 7.5 - 0.3 - 0.25 = 1.45 ns   (PASS)
// ===========================================================================
`timescale 1ns/1ps
`include "dnn_config.vh"

`ifndef GOLDEN_OUTPUT_PATH
  `define GOLDEN_OUTPUT_PATH "../golden/golden_output.memh"
`endif

module tb_zedboard_timing;

    // ----------------------------------------------------------------------
    // Timing parameters (override at compile time with -P or +define+)
    // ----------------------------------------------------------------------
    parameter real CLK_PERIOD_NS = 10.000;  // 100 MHz Zedboard PL clock
    parameter real T_CKO_NS      = 0.500;   // FDRE clk-to-Q
    parameter real T_SETUP_NS    = 0.300;   // FDRE setup
    parameter real T_HOLD_NS     = 0.100;   // FDRE hold
    parameter real T_COMB_NS     = 7.500;   // Modeled worst routed comb path
    parameter real T_UNCERT_NS   = 0.250;   // Jitter + skew uncertainty

    // ----------------------------------------------------------------------
    // System parameters from optimizer
    // ----------------------------------------------------------------------
    localparam NUM_LAYERS         = `DNN_NUM_LAYERS;
    localparam MEM_ADDR_W         = 20;
    localparam MEM_DATA_W         = 32;
    localparam EST_LATENCY_CYCLES = `DNN_EST_LATENCY_CYCLES;

    // ----------------------------------------------------------------------
    // Scoreboard
    // ----------------------------------------------------------------------
    integer tc_count;
    integer pass_count;
    integer fail_count;

    task automatic check_true;
        input [1023:0] name;
        input         cond;
        begin
            tc_count = tc_count + 1;
            if (cond) begin
                pass_count = pass_count + 1;
                $display("  PASS  [%0s]", name);
            end else begin
                fail_count = fail_count + 1;
                $display("  FAIL  [%0s]", name);
            end
        end
    endtask

    task automatic check_ge_real;
        input [1023:0] name;
        input real    actual;
        input real    threshold;
        begin
            tc_count = tc_count + 1;
            if (actual >= threshold) begin
                pass_count = pass_count + 1;
                $display("  PASS  [%0s]  actual=%0.3fns  threshold=%0.3fns",
                         name, actual, threshold);
            end else begin
                fail_count = fail_count + 1;
                $display("  FAIL  [%0s]  actual=%0.3fns  threshold=%0.3fns",
                         name, actual, threshold);
            end
        end
    endtask

    task automatic check_eq;
        input [1023:0] name;
        input integer got;
        input integer expected;
        begin
            tc_count = tc_count + 1;
            if (got === expected) begin
                pass_count = pass_count + 1;
                $display("  PASS  [%0s]  (=%0d)", name, got);
            end else begin
                fail_count = fail_count + 1;
                $display("  FAIL  [%0s]  got=%0d  expected=%0d",
                         name, got, expected);
            end
        end
    endtask

    task automatic banner;
        input [1023:0] title;
        begin
            $display("");
            $display("============================================================");
            $display(" %0s", title);
            $display("============================================================");
        end
    endtask

    // ----------------------------------------------------------------------
    // Clock generator at the Zedboard target frequency
    // ----------------------------------------------------------------------
    reg clk;
    initial begin
        clk = 0;
        forever #(CLK_PERIOD_NS / 2.0) clk = ~clk;
    end

    // ----------------------------------------------------------------------
    // TB-side driven signals (sources)
    // ----------------------------------------------------------------------
    reg rst_src;
    reg start_inference_src;
    reg load_weights_src;

    // ----------------------------------------------------------------------
    // Combinational-delay injection: model the source FF Tcko plus the routed
    // comb path with a procedural transport delay.  These delayed versions
    // are what the DUT actually sees.
    // ----------------------------------------------------------------------
    reg rst_dut;
    reg start_inference_dut;
    reg load_weights_dut;

    localparam real T_SRC_TO_DUT = T_CKO_NS + T_COMB_NS;

    always @(rst_src)             rst_dut             <= #(T_SRC_TO_DUT) rst_src;
    always @(start_inference_src) start_inference_dut <= #(T_SRC_TO_DUT) start_inference_src;
    always @(load_weights_src)    load_weights_dut    <= #(T_SRC_TO_DUT) load_weights_src;

    // ----------------------------------------------------------------------
    // Setup / hold monitor
    // ----------------------------------------------------------------------
    real last_change_si;
    real last_change_lw;
    real last_change_rst;
    real last_posedge_time;

    integer setup_violations;
    integer hold_violations;
    real    worst_setup_margin;
    real    worst_hold_margin;

    initial begin
        last_change_si      =  0.0;
        last_change_lw      =  0.0;
        last_change_rst     =  0.0;
        last_posedge_time   = -1.0;
        setup_violations    =  0;
        hold_violations     =  0;
        worst_setup_margin  =  1e9;
        worst_hold_margin   =  1e9;
    end

    always @(start_inference_dut) last_change_si  = $realtime;
    always @(load_weights_dut)    last_change_lw  = $realtime;
    always @(rst_dut)             last_change_rst = $realtime;

    // SETUP CHECK: at each posedge, time since last change must be >= T_SETUP
    task automatic check_setup;
        input real    change_time;
        input [255:0] sig_name;
        real time_since_change;
        real margin;
        begin
            if (change_time > 0.0 && change_time < $realtime) begin
                time_since_change = $realtime - change_time;
                margin = time_since_change - T_SETUP_NS;
                if (margin < worst_setup_margin) worst_setup_margin = margin;
                if (margin < 0.0) begin
                    setup_violations = setup_violations + 1;
                    if (setup_violations <= 5)
                        $display("  [SETUP VIOL] %0s: change %0.3fns before edge (need %0.3fns, margin %0.3fns)",
                                 sig_name, time_since_change, T_SETUP_NS, margin);
                end
            end
        end
    endtask

    always @(posedge clk) begin
        check_setup(last_change_si,  "start_inference");
        check_setup(last_change_lw,  "load_weights");
        check_setup(last_change_rst, "rst");
        last_posedge_time = $realtime;
    end

    // HOLD CHECK: when any monitored signal changes, change time must be
    // >= T_HOLD after the most recent posedge.
    task automatic check_hold;
        input [255:0] sig_name;
        real time_since_edge;
        real margin;
        begin
            if (last_posedge_time > 0.0) begin
                time_since_edge = $realtime - last_posedge_time;
                margin = time_since_edge - T_HOLD_NS;
                if (margin < worst_hold_margin) worst_hold_margin = margin;
                if (margin < 0.0) begin
                    hold_violations = hold_violations + 1;
                    if (hold_violations <= 5)
                        $display("  [HOLD VIOL]  %0s: change %0.3fns after edge (need %0.3fns, margin %0.3fns)",
                                 sig_name, time_since_edge, T_HOLD_NS, margin);
                end
            end
        end
    endtask

    always @(start_inference_dut) check_hold("start_inference");
    always @(load_weights_dut)    check_hold("load_weights");
    always @(rst_dut)             check_hold("rst");

    // ----------------------------------------------------------------------
    // Memory & DUT instance
    // ----------------------------------------------------------------------
    wire [MEM_ADDR_W-1:0] mem_addr;
    wire                  mem_read;
    reg  [MEM_DATA_W-1:0] mem_rdata;
    reg                   mem_rdata_valid;
    wire                  mem_write;
    wire [MEM_DATA_W-1:0] mem_wdata;

    reg  [MEM_ADDR_W-1:0] input_base_addr;
    reg  [MEM_ADDR_W-1:0] output_base_addr;
    reg  [MEM_ADDR_W*NUM_LAYERS-1:0] weights_base_addr;

    wire                  inference_done;
    wire                  system_ready;
    wire                  weights_loaded;
    wire [NUM_LAYERS-1:0] layer_busy;
    wire                  pipeline_active;

    reg  [MEM_DATA_W-1:0] memory [0:(1<<18)-1];

    streaming_nn_system #(
        .NUM_LAYERS (NUM_LAYERS),
        .MEM_ADDR_W (MEM_ADDR_W),
        .MEM_DATA_W (MEM_DATA_W)
    ) dut (
        .clk              (clk),
        .rst              (rst_dut),
        .start_inference  (start_inference_dut),
        .inference_done   (inference_done),
        .system_ready     (system_ready),
        .load_weights     (load_weights_dut),
        .weights_loaded   (weights_loaded),
        .mem_addr         (mem_addr),
        .mem_read         (mem_read),
        .mem_rdata        (mem_rdata),
        .mem_rdata_valid  (mem_rdata_valid),
        .mem_write        (mem_write),
        .mem_wdata        (mem_wdata),
        .input_base_addr  (input_base_addr),
        .output_base_addr (output_base_addr),
        .weights_base_addr(weights_base_addr),
        .layer_busy       (layer_busy),
        .pipeline_active  (pipeline_active)
    );

    // Simple 1-cycle latency memory
    always @(posedge clk) begin
        mem_rdata_valid <= 1'b0;
        if (mem_read) begin
            mem_rdata       <= memory[mem_addr];
            mem_rdata_valid <= 1'b1;
        end
        if (mem_write) begin
            memory[mem_addr] <= mem_wdata;
        end
    end

    // ----------------------------------------------------------------------
    // Memory initialization (matches comprehensive TB exactly)
    // ----------------------------------------------------------------------
    integer i;
    task automatic init_memory;
        begin
            for (i = 0; i < (1<<18); i = i + 1) memory[i] = {MEM_DATA_W{1'b0}};
            for (i = 0; i < 784; i = i + 1)
                memory[input_base_addr + i] = (i % 256) << 8;
            for (i = 0; i < 150; i = i + 1)
                memory[weights_base_addr[MEM_ADDR_W*1-1 -: MEM_ADDR_W] + i]
                    = ((i * 7 + 3) & 16'hFF) << 4;
            for (i = 0; i < 2400; i = i + 1)
                memory[weights_base_addr[MEM_ADDR_W*3-1 -: MEM_ADDR_W] + i]
                    = ((i * 13 + 5) & 16'hFF) << 4;
        end
    endtask

    // ----------------------------------------------------------------------
    // Negedge-driven pulse helpers
    // ----------------------------------------------------------------------
    task automatic pulse_load_weights;
        begin
            @(negedge clk);
            load_weights_src = 1'b1;
            @(negedge clk);
            load_weights_src = 1'b0;
        end
    endtask

    task automatic pulse_start_inference;
        begin
            @(negedge clk);
            start_inference_src = 1'b1;
            @(negedge clk);
            start_inference_src = 1'b0;
        end
    endtask

    task automatic do_reset;
        begin
            rst_src             = 1'b1;
            start_inference_src = 1'b0;
            load_weights_src    = 1'b0;
            repeat (10) @(posedge clk);
            @(negedge clk);
            rst_src = 1'b0;
            repeat (5) @(posedge clk);
        end
    endtask

    // ----------------------------------------------------------------------
    // Golden-output scoreboard
    // ----------------------------------------------------------------------
    reg  [15:0] golden_out [0:255];
    integer     gold_i, gold_matches, gold_mismatches, gold_max_abs_diff;
    integer     gold_diff;
    reg  [15:0] gold_hw_val;

    // ----------------------------------------------------------------------
    // Watchdog
    // ----------------------------------------------------------------------
    initial begin
        #(10.0 * EST_LATENCY_CYCLES * CLK_PERIOD_NS + 1_000_000);
        $display("");
        $display(">>> TIMEOUT — simulation exceeded global watchdog <<<");
        $finish;
    end

    // ----------------------------------------------------------------------
    // VCD
    // ----------------------------------------------------------------------
    initial begin
        $dumpfile("tb_zedboard_timing.vcd");
        $dumpvars(0, tb_zedboard_timing);
    end

    // ----------------------------------------------------------------------
    // Main test sequence
    // ----------------------------------------------------------------------
    real    slack_ns;
    integer guard_left;

    initial begin
        tc_count            = 0;
        pass_count          = 0;
        fail_count          = 0;
        rst_src             = 1'b1;
        start_inference_src = 1'b0;
        load_weights_src    = 1'b0;
        rst_dut             = 1'b1;
        start_inference_dut = 1'b0;
        load_weights_dut    = 1'b0;

        slack_ns = CLK_PERIOD_NS - T_CKO_NS - T_COMB_NS - T_SETUP_NS - T_UNCERT_NS;

        $display("############################################################");
        $display("#       ZEDBOARD TIMING-VERIFICATION TESTBENCH");
        $display("############################################################");
        $display("# Target part   : XC7Z020-1CLG484 (ZedBoard, speed grade -1)");
        $display("# Clock period  : %0.3f ns  (%0.1f MHz)", CLK_PERIOD_NS,
                 1000.0 / CLK_PERIOD_NS);
        $display("# Tcko          : %0.3f ns", T_CKO_NS);
        $display("# T_comb (model): %0.3f ns", T_COMB_NS);
        $display("# Tsetup        : %0.3f ns", T_SETUP_NS);
        $display("# Thold         : %0.3f ns", T_HOLD_NS);
        $display("# Uncertainty   : %0.3f ns", T_UNCERT_NS);
        $display("# ------------------------------------------------------------");
        $display("# Setup slack   : %0.3f ns  (period - Tcko - Tcomb - Tsu - U)", slack_ns);
        $display("############################################################");

        banner("TT1: Period budget vs combinational + setup");
        check_ge_real("TT1.slack_nonnegative", slack_ns, 0.0);

        input_base_addr  = 20'h00000;
        output_base_addr = 20'h10000;
        weights_base_addr[MEM_ADDR_W*1-1 -: MEM_ADDR_W] = 20'h20000;
        weights_base_addr[MEM_ADDR_W*2-1 -: MEM_ADDR_W] = 20'h20100;
        weights_base_addr[MEM_ADDR_W*3-1 -: MEM_ADDR_W] = 20'h30000;
        weights_base_addr[MEM_ADDR_W*4-1 -: MEM_ADDR_W] = 20'h30A00;

        init_memory();
        do_reset();

        banner("TT2: Reset/ready at 100 MHz with injected delays");
        repeat (20) @(posedge clk);
        check_true("TT2.system_ready_after_reset", system_ready === 1'b1);

        banner("TT3: Weight load survives delayed load_weights");
        pulse_load_weights();
        guard_left = 200000;
        while (!weights_loaded && guard_left > 0) begin
            @(posedge clk);
            guard_left = guard_left - 1;
        end
        check_true("TT3.weights_loaded_under_delay", weights_loaded === 1'b1);

        banner("TT4: Full inference at Zedboard frequency");
        wait (system_ready);
        @(posedge clk);
        pulse_start_inference();
        guard_left = 10 * EST_LATENCY_CYCLES;
        while (!inference_done && guard_left > 0) begin
            @(posedge clk);
            guard_left = guard_left - 1;
        end
        check_true("TT4.inference_done_under_delay", inference_done === 1'b1);
        repeat (30) @(posedge clk);

        banner("TT5: Golden-reference comparison under timing model");
        $readmemh(`GOLDEN_OUTPUT_PATH, golden_out);
        gold_matches      = 0;
        gold_mismatches   = 0;
        gold_max_abs_diff = 0;
        for (gold_i = 0; gold_i < 256; gold_i = gold_i + 1) begin
            gold_hw_val = memory[output_base_addr + gold_i][15:0];
            if (gold_hw_val === golden_out[gold_i]) begin
                gold_matches = gold_matches + 1;
            end else begin
                gold_mismatches = gold_mismatches + 1;
                gold_diff = $signed({1'b0, gold_hw_val}) -
                            $signed({1'b0, golden_out[gold_i]});
                if (gold_diff < 0) gold_diff = -gold_diff;
                if (gold_diff > gold_max_abs_diff) gold_max_abs_diff = gold_diff;
            end
        end
        $display("  golden matches    : %0d / 256",  gold_matches);
        $display("  golden mismatches : %0d",        gold_mismatches);
        $display("  max |hw-golden|   : %0d",        gold_max_abs_diff);
        check_eq("TT5.golden_exact_match_under_delay", gold_mismatches, 0);

        banner("TT6: Behavioral setup-margin observed across whole run");
        $display("  worst observed setup margin : %0.3f ns", worst_setup_margin);
        $display("  setup violations            : %0d",      setup_violations);
        check_eq("TT6.no_setup_violations", setup_violations, 0);
        check_ge_real("TT6.setup_margin_positive", worst_setup_margin, 0.0);

        banner("TT7: Behavioral hold-margin observed across whole run");
        $display("  worst observed hold margin  : %0.3f ns", worst_hold_margin);
        $display("  hold violations             : %0d",      hold_violations);
        check_eq("TT7.no_hold_violations", hold_violations, 0);
        check_ge_real("TT7.hold_margin_positive", worst_hold_margin, 0.0);

        banner("TT8: Final timing-verification report");
        $display("");
        $display("  Target part       : XC7Z020-1CLG484 (ZedBoard)");
        $display("  Clock frequency   : %0.1f MHz",   1000.0 / CLK_PERIOD_NS);
        $display("  Period            : %0.3f ns",     CLK_PERIOD_NS);
        $display("  Setup budget used : %0.3f ns / %0.3f ns",
                 T_CKO_NS + T_COMB_NS + T_SETUP_NS + T_UNCERT_NS, CLK_PERIOD_NS);
        $display("  Setup slack       : %0.3f ns",     slack_ns);
        $display("  Worst setup obs   : %0.3f ns",     worst_setup_margin);
        $display("  Worst hold obs    : %0.3f ns",     worst_hold_margin);
        $display("");
        $display("  Tests run   : %0d", tc_count);
        $display("  Pass        : %0d", pass_count);
        $display("  Fail        : %0d", fail_count);
        if (fail_count == 0)
            $display("  >>> TIMING VERIFICATION PASSED <<<");
        else
            $display("  >>> %0d TIMING TEST(S) FAILED <<<", fail_count);
        $display("");
        $finish;
    end

endmodule
