#!/usr/bin/env python3
"""
generate_config.py
==================
Stage 1 of the Vivado flow pipeline.

Accepts EITHER:
  a) A TensorFlow/Keras model  → extracts the first Conv2D layer's dimensions
  b) Explicit layer dimensions  → uses them directly

Runs:
  1. LoopOptimizer   – finds the best 6-D loop order (720 permutations)
  2. BlockingOptimizer – finds tile sizes that minimise DRAM traffic

Emits:
  • configs/generated/optimal_config.vh  – `define macros for Verilog
  • configs/generated/optimal_config.json – machine-readable summary

Usage
-----
  # From explicit dims
  python generate_config.py \
      --K 16 --C 8 --KH 3 --KW 3 --H 30 --W 30 \
      --array-height 4 --array-width 4

  # From a TF model (first Conv2D layer)
  python generate_config.py --tf-model mobilenet_v2

  # From a TF model, specific layer index
  python generate_config.py --tf-model tiny_cnn --layer-idx 2
"""

from __future__ import annotations
import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, Optional, Tuple

# ---------------------------------------------------------------------------
# Resolve src/ on sys.path so imports work regardless of cwd
# ---------------------------------------------------------------------------
_HERE   = Path(__file__).resolve().parent          # vivado_flow/optimizer/
_ROOT   = _HERE.parent.parent                      # repo root
_SRC    = _ROOT / "systolic_optimizer_codebase" / "systolic_optimizer" / "src"
for _p in [str(_SRC), str(_HERE)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from loop_optimizer     import LoopOptimizer, LoopTileConfig
from blocking_optimizer import BlockingOptimizer, SearchMode

# ── Cross-platform UTF-8 stdout/stderr ──────────────────────────────────────
# Windows consoles default to CP1252 which cannot encode → ✓ ✗ etc.
# reconfigure() forces UTF-8 for both interactive runs and log-file redirects.
# On Linux/macOS this is a harmless no-op (stdout is already UTF-8).
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# ---------------------------------------------------------------------------
# Output directory
# ---------------------------------------------------------------------------
_OUT_DIR = _HERE.parent / "configs" / "generated"
_OUT_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Loop-order enum → integer encoding for Verilog
# ---------------------------------------------------------------------------
_LOOP_ORDER_CODES: Dict[Tuple[str,...], int] = {}

def _build_order_codes():
    """Assign stable integer codes to all named LoopOrder6D presets."""
    from loop_optimizer import LoopOrder6D
    for idx, order in enumerate(LoopOrder6D):
        _LOOP_ORDER_CODES[order.value] = idx

_build_order_codes()


# ---------------------------------------------------------------------------
# Verilog header emitter
# ---------------------------------------------------------------------------

def emit_verilog_header(
    dims:       Dict,
    loop_order: Tuple[str, ...],
    blocking:   Dict,
    array_h:    int,
    array_w:    int,
    data_width: int = 32,
    accum_width: int= 48,
    addr_width: int = 32,
    layer_name: str = "conv_layer",
    output_path: Optional[Path] = None,
) -> Path:
    """
    Write a Verilog header file containing all parameters the testbench needs.

    Verilog `define` macros keep the header self-contained and tool-agnostic
    (no `package` dependency).  The testbench includes this file before
    the module declaration via a backtick-include directive.

    Returns the path of the written file.
    """
    if output_path is None:
        output_path = _OUT_DIR / "optimal_config.vh"

    order_str  = "->".join(loop_order)
    order_code = _LOOP_ORDER_CODES.get(loop_order, 99)   # 99 = custom

    lines = [
        "//============================================================",
        "// AUTO-GENERATED by generate_config.py – DO NOT EDIT MANUALLY",
        "//============================================================",
        "",
        f"// Layer: {layer_name}",
        f"// Loop order: {order_str}  (code {order_code})",
        "",
        "// ---- Hardware array geometry --------------------------------",
        f"`define ARRAY_HEIGHT   {array_h}",
        f"`define ARRAY_WIDTH    {array_w}",
        f"`define DATA_WIDTH     {data_width}",
        f"`define ACCUM_WIDTH    {accum_width}",
        f"`define ADDR_WIDTH     {addr_width}",
        "",
        "// ---- Layer dimensions ---------------------------------------",
        f"`define LAYER_K        {dims['K']}   // output channels",
        f"`define LAYER_C        {dims['C']}   // input  channels",
        f"`define LAYER_KH       {dims['KH']}  // kernel height",
        f"`define LAYER_KW       {dims['KW']}  // kernel width",
        f"`define LAYER_H_IN     {dims['H']}   // input feature height",
        f"`define LAYER_W_IN     {dims['W']}   // input feature width",
        f"`define LAYER_H_OUT    {dims['H'] - dims['KH'] + 1}",
        f"`define LAYER_W_OUT    {dims['W'] - dims['KW'] + 1}",
        "",
        "// ---- Optimal tiling -----------------------------------------",
        f"`define TILE_K         {blocking['tile_K']}",
        f"`define TILE_C         {blocking['tile_C']}",
        f"`define TILE_H         {blocking['tile_H']}",
        f"`define TILE_W         {blocking['tile_W']}",
        "",
        "// ---- Optimal loop order (6-D, encoded as integer) -----------",
        f"// {order_str}",
        f"`define LOOP_ORDER     {order_code}",
        "",
        "// ---- Memory layout (0=NHWC / 1=NCHW) -----------------------",
        "`define MEM_LAYOUT     0",
        "",
        "// ---- Base addresses (byte offsets into flat SRAM) -----------",
        "`define INPUT_BASE_ADDR   32'h0000_0000",
        f"`define WEIGHT_BASE_ADDR  32'h{dims['H'] * dims['W'] * dims['C'] * 4:08X}",
        f"`define OUTPUT_BASE_ADDR  32'h{dims['H'] * dims['W'] * dims['C'] * 4 + dims['K'] * dims['C'] * dims['KH'] * dims['KW'] * 4:08X}",
        "",
        "// ---- Simulation budget (cycles) -----------------------------",
        f"// Worst-case estimate: 4 × tiles × pipeline depth",
        f"`define SIM_TIMEOUT    {_sim_timeout(dims, blocking, array_h, array_w)}",
        "",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[generate_config] Wrote Verilog header → {output_path}")
    return output_path


def _sim_timeout(dims, blocking, array_h, array_w) -> int:
    """Conservative cycle budget for the testbench watchdog."""
    import math
    n_tiles_k  = math.ceil(dims['K'] / max(blocking['tile_K'], 1))
    n_tiles_c  = math.ceil(dims['C'] / max(blocking['tile_C'], 1))
    n_tiles_h  = math.ceil(dims['H'] / max(blocking['tile_H'], 1))
    n_tiles_w  = math.ceil(dims['W'] / max(blocking['tile_W'], 1))
    kh, kw     = dims['KH'], dims['KW']
    pipe_depth = array_h + array_w + 10           # generous pipeline flush
    total_tiles= n_tiles_k * n_tiles_c * n_tiles_h * n_tiles_w * kh * kw
    return max(50_000, total_tiles * pipe_depth * 4)


# ---------------------------------------------------------------------------
# JSON summary
# ---------------------------------------------------------------------------

def emit_json_summary(
    dims:       Dict,
    loop_order: Tuple[str,...],
    loop_metrics: Dict,
    blocking_cfg: object,
    blocking_metrics: Dict,
    array_h: int,
    array_w: int,
    output_path: Optional[Path] = None,
) -> Path:
    if output_path is None:
        output_path = _OUT_DIR / "optimal_config.json"

    summary = {
        "layer_dims":  dims,
        "array":       {"height": array_h, "width": array_w},
        "loop_order":  list(loop_order),
        "loop_metrics": {
            k: (v if not hasattr(v, 'value') else v.value)
            for k, v in loop_metrics.items()
        },
        "blocking": {
            "tile_K":  blocking_cfg.blocking.tile_K,
            "tile_C":  blocking_cfg.blocking.tile_C,
            "tile_H":  blocking_cfg.blocking.tile_H,
            "tile_W":  blocking_cfg.blocking.tile_W,
            "inner_h": blocking_cfg.blocking.inner_h,
            "inner_w": blocking_cfg.blocking.inner_w,
        },
        "blocking_metrics": {
            k: float(v) if isinstance(v, (int, float)) else v
            for k, v in blocking_metrics.items()
        },
    }

    output_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"[generate_config] Wrote JSON summary     → {output_path}")
    return output_path


# ---------------------------------------------------------------------------
# TF model extraction
# ---------------------------------------------------------------------------

def dims_from_tf_model(model_name: str, layer_idx: int = 0) -> Tuple[Dict, str]:
    """
    Load a named Keras application or the tiny_cnn demo model and extract
    the dimensions of the first Conv2D layer (or the one at layer_idx).

    Returns (dims_dict, layer_name).
    """
    os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")
    try:
        import tensorflow as tf
    except ImportError:
        raise RuntimeError(
            "TensorFlow is not installed.  Install it with:\n"
            "    pip install tensorflow\n"
            "or pass explicit --K --C --KH --KW --H --W flags instead."
        )

    # Built-in Keras applications
    _APPS = {
        "mobilenet_v2":  tf.keras.applications.MobileNetV2,
        "resnet50":      tf.keras.applications.ResNet50,
        "efficientnetb0":tf.keras.applications.EfficientNetB0,
        "vgg16":         tf.keras.applications.VGG16,
        "inception_v3":  tf.keras.applications.InceptionV3,
    }

    mn = model_name.lower()
    if mn in _APPS:
        print(f"[generate_config] Loading {model_name} (weights=None) …")
        model = _APPS[mn](weights=None, include_top=True)
    elif mn == "tiny_cnn":
        print("[generate_config] Building tiny_cnn demo model …")
        inp = tf.keras.Input(shape=(32, 32, 3))
        x   = tf.keras.layers.Conv2D(16, 3, padding="same", name="conv1")(inp)
        x   = tf.keras.layers.Conv2D(32, 3, name="conv2")(x)
        x   = tf.keras.layers.GlobalAveragePooling2D()(x)
        x   = tf.keras.layers.Dense(10)(x)
        model = tf.keras.Model(inp, x, name="tiny_cnn")
    else:
        raise ValueError(
            f"Unknown model name '{model_name}'.  "
            f"Known: {list(_APPS.keys()) + ['tiny_cnn']}"
        )

    # Walk layers to find Conv2D at layer_idx
    conv_layers = [l for l in model.layers
                   if isinstance(l, tf.keras.layers.Conv2D)]
    if not conv_layers:
        raise RuntimeError("No Conv2D layers found in the model.")

    idx = min(layer_idx, len(conv_layers) - 1)
    layer = conv_layers[idx]
    cfg   = layer.get_config()

    # Output shape: (None, H, W, K)
    out_sh = layer.output_shape   # may raise if model not built
    in_sh  = layer.input_shape    # (None, H_in, W_in, C)

    kh, kw = cfg["kernel_size"]
    K      = cfg["filters"]
    C      = in_sh[-1]
    H_in   = in_sh[1]
    W_in   = in_sh[2]

    dims = dict(K=K, C=C, KH=kh, KW=kw, H=H_in, W=W_in)
    print(f"[generate_config] Layer '{layer.name}': K={K} C={C} "
          f"KH={kh} KW={kw} H_in={H_in} W_in={W_in}")
    return dims, layer.name


# ---------------------------------------------------------------------------
# Main optimisation routine
# ---------------------------------------------------------------------------

def run(
    dims:       Dict,
    array_h:    int = 4,
    array_w:    int = 4,
    data_width: int = 32,
    accum_width:int = 48,
    addr_width: int = 32,
    search_mode:str = "heuristic",
    target:     str = "balanced",
    layer_name: str = "conv_layer",
    vh_path:    Optional[Path] = None,
    json_path:  Optional[Path] = None,
) -> Tuple[Path, Path]:
    """
    Run optimisers and emit both output files.

    Returns (vh_path, json_path).
    """
    print("\n" + "=" * 60)
    print("STEP 1 — Loop-order optimisation (LoopOptimizer)")
    print("=" * 60)
    lo = LoopOptimizer(array_height=array_h, array_width=array_w)
    tile_cfg = LoopTileConfig(
        tile_k=min(array_h, dims['K']),
        tile_c=min(array_w, dims['C']),
        tile_hin=array_h,
        tile_win=array_w,
    )
    best_order, all_lo = lo.find_optimal_loop_order(
        k=dims['K'], c=dims['C'], kh=dims['KH'], kw=dims['KW'],
        h_in=dims['H'], w_in=dims['W'],
        tile_config=tile_cfg,
        target=target,
        exhaustive=False,
    )
    best_order_tuple = best_order.value
    best_lo_metrics  = all_lo[best_order]
    arrow = "->"
    print(f"\n  Best loop order : {arrow.join(best_order_tuple)}")
    print(f"  Weight reuse    : {best_lo_metrics['weight_reuse']:.2f}x")
    print(f"  Input  reuse    : {best_lo_metrics['input_reuse']:.2f}x")
    print(f"  Output reuse    : {best_lo_metrics['output_reuse']:.2f}x")

    print("\n" + "=" * 60)
    print("STEP 2 — Tile-size optimisation (BlockingOptimizer)")
    print("=" * 60)
    mode_map = {
        "heuristic":  SearchMode.HEURISTIC,
        "exhaustive": SearchMode.EXHAUSTIVE,
        "gradient":   SearchMode.GRADIENT,
    }
    bo = BlockingOptimizer(
        K=dims['K'], C=dims['C'], H=dims['H'], W=dims['W'],
        KH=dims['KH'], KW=dims['KW'],
        array_height=array_h, array_width=array_w,
    )
    best_cfg, all_bo = bo.search(
        mode=mode_map.get(search_mode, SearchMode.HEURISTIC),
        objective="min_traffic",
        verbose=False,   # suppress Unicode box-drawing output (codepage issue)
    )
    blocking = {
        "tile_K":  best_cfg.blocking.tile_K,
        "tile_C":  best_cfg.blocking.tile_C,
        "tile_H":  best_cfg.blocking.tile_H,
        "tile_W":  best_cfg.blocking.tile_W,
    }
    best_bo_metrics = all_bo[str(best_cfg)]
    # Print results in plain ASCII
    print(f"\n  Best blocking   : {best_cfg}")
    dram_mb = best_bo_metrics.get("dram_traffic", 0) / 1e6
    spad_kb = best_bo_metrics.get("scratchpad_need", 0) / 1024
    fits    = best_bo_metrics.get("scratchpad_fits", True)
    print(f"  DRAM traffic    : {dram_mb:.4f} MB")
    print(f"  Scratchpad      : {spad_kb:.1f} KB  ({'fits' if fits else 'overflow'})")

    print("\n" + "=" * 60)
    print("STEP 3 — Emitting output files")
    print("=" * 60)
    vh   = emit_verilog_header(
        dims, best_order_tuple, blocking,
        array_h, array_w, data_width, accum_width, addr_width,
        layer_name=layer_name, output_path=vh_path,
    )
    jsn  = emit_json_summary(
        dims, best_order_tuple,
        {"weight_reuse": best_lo_metrics['weight_reuse'],
         "input_reuse":  best_lo_metrics['input_reuse'],
         "output_reuse": best_lo_metrics['output_reuse'],
         "score":        best_lo_metrics.get('score', 0.0)},
        best_cfg, best_bo_metrics,
        array_h, array_w, output_path=json_path,
    )
    return vh, jsn


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Run loop + tile optimiser and emit Verilog / JSON config."
    )
    # Source (mutually exclusive)
    src = p.add_mutually_exclusive_group()
    src.add_argument("--tf-model", metavar="NAME",
                     help="Keras application name or 'tiny_cnn'")
    src.add_argument("--K",  type=int, help="Output channels")

    # Explicit dims (only used when --K is given)
    p.add_argument("--C",   type=int, default=8,  help="Input channels")
    p.add_argument("--KH",  type=int, default=3,  help="Kernel height")
    p.add_argument("--KW",  type=int, default=3,  help="Kernel width")
    p.add_argument("--H",   type=int, default=28, help="Input height")
    p.add_argument("--W",   type=int, default=28, help="Input width")

    # TF-model options
    p.add_argument("--layer-idx", type=int, default=0,
                   help="Which Conv2D layer to extract (0 = first)")

    # Array hardware
    p.add_argument("--array-height", type=int, default=4)
    p.add_argument("--array-width",  type=int, default=4)
    p.add_argument("--data-width",   type=int, default=32)
    p.add_argument("--accum-width",  type=int, default=48)

    # Search
    p.add_argument("--search-mode", choices=["heuristic","exhaustive","gradient"],
                   default="heuristic")
    p.add_argument("--target",
                   choices=["weight_reuse","input_reuse","output_reuse","balanced"],
                   default="balanced")

    # Output
    p.add_argument("--vh-out",   type=Path, default=None,
                   help="Override Verilog header output path")
    p.add_argument("--json-out", type=Path, default=None,
                   help="Override JSON summary output path")
    return p


def main(argv=None):
    args = _build_parser().parse_args(argv)

    if args.tf_model:
        dims, layer_name = dims_from_tf_model(args.tf_model, args.layer_idx)
    elif args.K is not None:
        dims = dict(K=args.K, C=args.C, KH=args.KH, KW=args.KW,
                    H=args.H, W=args.W)
        layer_name = "manual_layer"
    else:
        # Fallback demo
        print("[generate_config] No source specified — using demo dims.")
        dims = dict(K=16, C=8, KH=3, KW=3, H=30, W=30)
        layer_name = "demo_layer"

    vh, jsn = run(
        dims=dims,
        array_h=args.array_height,
        array_w=args.array_width,
        data_width=args.data_width,
        accum_width=args.accum_width,
        search_mode=args.search_mode,
        target=args.target,
        layer_name=layer_name,
        vh_path=args.vh_out,
        json_path=args.json_out,
    )

    print("\n✓ Done.")
    print(f"  Verilog header : {vh}")
    print(f"  JSON summary   : {jsn}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
