#!/usr/bin/env python3
"""
memh_to_c.py — convert Verilog $readmemh() files into a C const-array.

Usage:
    python3 memh_to_c.py <l0.memh> <l3.memh>  > yolo_weights.c

Each .memh file contains one hex number per line (16-bit values for our
Q8.8/Q4.12 fixed-point weights). Comments (// ...) are ignored.
"""
import re
import sys
from pathlib import Path


def load_memh(path: Path) -> list[int]:
    vals: list[int] = []
    for raw in path.read_text().splitlines():
        line = re.sub(r"//.*$", "", raw).strip()
        if not line:
            continue
        # Some files use multiple tokens per line
        for tok in line.split():
            v = int(tok, 16)
            # interpret 16-bit two's complement → signed
            if v & 0x8000:
                v -= 0x10000
            vals.append(v)
    return vals


def emit_array(name: str, vals: list[int]) -> None:
    print(f"const s16 {name}[{len(vals)}] = {{")
    for i in range(0, len(vals), 8):
        chunk = ", ".join(f"{v:6d}" for v in vals[i:i + 8])
        print(f"    {chunk},")
    print("};")


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 1
    l0 = load_memh(Path(sys.argv[1]))
    l3 = load_memh(Path(sys.argv[2]))
    print("/* Auto-generated by memh_to_c.py — do not edit by hand. */")
    print("#include \"yolo_weights.h\"")
    print()
    emit_array("yolo_wgt_l0", l0)
    print()
    emit_array("yolo_wgt_l3", l3)
    return 0


if __name__ == "__main__":
    sys.exit(main())
