#!/usr/bin/env python3
"""Generate analytic 'bright-quadrant detector' weights for the live demo,
verify them against the bit-exact golden model, and emit dnn_weights.h.

Design (fixed topology: CONV3x3 1->4 / POOL / POOL / FC 36->20):
  L0 ch0 = identity (center tap +1)  -> brightness map
  L0 ch1..3 = 0
  After the two max-pools, L2 ch0 is a 3x3 grid of regional max brightness
  (units: luma*256 because preprocess shifts luma <<8).
  FC cell c: conf/w/h/x/y = corner(c) - center, corners (0,0) (0,2) (2,0)
  (2,2) of the 3x3 grid, center (1,1) as ambient reference.
  Host decode uses (s32 >> 8): conf = (corner_luma - center_luma)/256 in
  Q8.8, i.e. 0..1.0 for 0..255 luma contrast. Threshold 0.30 = 77 luma.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from golden_model import conv3x3_relu, maxpool2x2, fc  # noqa: E402

# ---- build weights ----------------------------------------------------------
wgt_l0 = [0] * 36            # co*9 + kr*3 + kc  (ci=0 only)
wgt_l0[0 * 9 + 1 * 3 + 1] = 1   # ch0 center tap = +1

wgt_l3 = [0] * 720           # o*36 + (ci*9 + r*3 + c)
corners = {0: (0, 0), 1: (0, 2), 2: (2, 0), 3: (2, 2)}
center = (1, 1)

def l2_idx(ci, r, c):
    return ci * 9 + r * 3 + c

for cell, (cr, cc) in corners.items():
    for p in range(5):       # x, y, w, h, conf all use the same contrast
        o = cell * 5 + p
        # own corner +3, other corners -1: uniform scenes cancel to zero and
        # a fixed bright source near the view CENTER cannot bias anything.
        wgt_l3[o * 36 + l2_idx(0, cr, cc)] = 3
        for other, (orr, occ) in corners.items():
            if other != cell:
                wgt_l3[o * 36 + l2_idx(0, orr, occ)] = -1

# ---- verify through the golden model ---------------------------------------
def run(scene16):
    act16 = [[v << 7 for v in row] for row in scene16]   # preprocess luma<<7 (s16-safe)
    l0 = conv3x3_relu(act16, wgt_l0)
    l1 = maxpool2x2(l0, 14, 14, 4)
    l2 = maxpool2x2(l1, 7, 7, 4)
    return fc(l2, wgt_l3)

def decode(raw):
    dets = []
    for c in range(4):
        conf = raw[c * 5 + 4] >> 8          # scale-shift decode
        if conf >= 77:                       # 0.30 in Q8.8
            dets.append((c, conf / 256.0))
    return dets

flat = [[60] * 16 for _ in range(16)]                     # uniform room
bright_tl = [row[:] for row in flat]
for y in range(1, 5):
    for x in range(1, 5):
        bright_tl[y][x] = 230                             # torch top-left
bright_br = [row[:] for row in flat]
for y in range(11, 15):
    for x in range(11, 15):
        bright_br[y][x] = 250                             # torch bottom-right
grad = [[(y * 8 + x) for x in range(16)] for y in range(16)]  # mild gradient

bright_ctr = [row[:] for row in flat]
for y in range(6, 8):
    for x in range(6, 8):
        bright_ctr[y][x] = 240                            # small central lamp

tests = [
    ("uniform scene   ", flat,      []),
    ("bright center   ", bright_ctr, []),
    ("bright top-left ", bright_tl, [0]),
    ("bright bot-right", bright_br, [3]),
    ("mild gradient   ", grad,      []),
]

ok = True
for name, scene, want in tests:
    dets = decode(run(scene))
    got = [c for c, _ in dets]
    status = "PASS" if got == want else "FAIL"
    if got != want:
        ok = False
    print(f"{name}: detections={dets}  expected cells={want}  {status}")

if not ok:
    sys.exit("weight design FAILED verification")

# ---- emit header ------------------------------------------------------------
out = Path(__file__).parent.parent / "software/linux/dnn_weights.h"
with open(out, "w") as f:
    f.write("/* Bright-quadrant detector weights — generated by "
            "tools/make_demo_weights.py.\n"
            " * conf[cell] = (corner region luma - center region luma), "
            "decoded via >>8.\n * Verified against the golden model. */\n")
    f.write("#ifndef DNN_WEIGHTS_H_\n#define DNN_WEIGHTS_H_\n\n")
    for name, arr in (("yolo_wgt_l0", wgt_l0), ("yolo_wgt_l3", wgt_l3)):
        f.write(f"static const short {name}[{len(arr)}] = {{\n")
        for i in range(0, len(arr), 12):
            f.write("    " + ", ".join(f"{v:4d}" for v in arr[i:i+12]) + ",\n")
        f.write("};\n\n")
    f.write("#endif\n")
print(f"\nwrote {out}")
