# =============================================================================
# zedboard_ps.xdc
#
# Constraints for the Zynq-attached DNN accelerator build (system_wrapper top).
# Everything DDR/USB/UART related is owned by the PS via MIO; the only PL pins
# we need are the four status LEDs.
#
# Board : Avnet ZedBoard (Rev D), XC7Z020-1CLG484
# Tool  : Vivado 2022.x
# Top   : system_wrapper  (generated by build_zynq_system.tcl)
# =============================================================================

# LD0..LD3 (Bank 33, 3.3 V fixed)
set_property PACKAGE_PIN T22 [get_ports {leds[0]}]
set_property PACKAGE_PIN T21 [get_ports {leds[1]}]
set_property PACKAGE_PIN U22 [get_ports {leds[2]}]
set_property PACKAGE_PIN U21 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[*]}]

# Informational only — keep them off the timing critical path
set_false_path -to [get_ports {leds[*]}]

# Bitstream config (Zynq boots from QSPI/SD; PROG_B handled by PS)
set_property CFGBVS VCCO          [current_design]
set_property CONFIG_VOLTAGE 3.3   [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]

# ----- USB OTG (informational) -------------------------------------------------
# The ZedBoard wires the on-board USB3320 ULPI PHY to MIO 28..39 on Bank 501.
# These are PS pins; no XDC entry is needed because the Zynq PS preset
# (em.avnet.com:zed:part0:1.4) takes care of MIO assignment when USB0 is
# enabled. The OTG ID/Vbus is handled by the PHY.
#
# Verify after build:
#   open_run impl_1
#   report_io  -> all USB0_* should show "MIO" in the Location column.
# ----- UART (informational) ----------------------------------------------------
# UART1 is on MIO 48 (TX) / 49 (RX), routed to the on-board Cypress USB-UART
# bridge → enumerates as /dev/ttyACM0 on Linux host at 115200 8N1.
